import type { Finding, Severity } from '../types';

const FENCE_LANG: Record<string, string> = {
  yaml: 'yaml',
  json: 'json',
  dockerfile: 'dockerfile',
};

const SEV_LABEL: Record<Severity, string> = {
  error: 'Errors',
  warning: 'Warnings',
  info: 'Info',
};

function plural(n: number, word: string): string {
  return `${n} ${word}${n === 1 ? '' : 's'}`;
}

/** Render findings + source as a single markdown block ready to paste into an LLM. */
export function findingsToMarkdown(
  source: string,
  findings: Finding[],
  language: 'yaml' | 'dockerfile' | 'json',
): string {
  const fence = FENCE_LANG[language] ?? '';
  const counts = {
    error: findings.filter((f) => f.severity === 'error').length,
    warning: findings.filter((f) => f.severity === 'warning').length,
    info: findings.filter((f) => f.severity === 'info').length,
  };
  const total = findings.length;

  const lines: string[] = [];
  lines.push(
    `# lintctl findings — ${plural(total, 'issue')} (${counts.error} error${
      counts.error === 1 ? '' : 's'
    }, ${counts.warning} warning${counts.warning === 1 ? '' : 's'}, ${counts.info} info)`,
  );
  lines.push(`Detected language: ${language}`);
  lines.push('');
  lines.push('## Source');
  lines.push('```' + fence);
  lines.push(source.replace(/\s+$/, ''));
  lines.push('```');
  lines.push('');

  if (total > 0) {
    lines.push('## Findings');
    for (const sev of ['error', 'warning', 'info'] as Severity[]) {
      const group = findings
        .filter((f) => f.severity === sev)
        .sort((a, b) => a.pos.line - b.pos.line);
      if (!group.length) continue;
      lines.push('');
      lines.push(`### ${SEV_LABEL[sev]} (${group.length})`);
      for (const f of group) {
        lines.push(
          `- **L${f.pos.line}:${f.pos.column}** \`${f.ruleId}\` — ${f.message}`,
        );
      }
    }
    lines.push('');
    lines.push('## Task');
    lines.push(
      'For each finding above, propose a concrete fix to the source. Show the corrected snippet and explain in one sentence why the change is safe.',
    );
  } else {
    lines.push('## Findings');
    lines.push('No issues found by static analysis.');
  }

  lines.push('');
  lines.push('---');
  lines.push('Generated by lintctl · https://usectl.com');
  return lines.join('\n');
}
